### ISSUE TITLE
Error loading syntax file - Sublime 3114

### ISSUE THREAD

**Issue by robotroll** [SublimeText/NSIS#32]
Hello,

with Sublime 3114 the syntax file for Nsis is causing following error:
![image](https://cloud.githubusercontent.com/assets/3962624/15311825/02d1c87e-1bff-11e6-9ce8-ea0aba36a237.png)

The corresponding lines in the file are:
```
- match: (\!include|\!insertmacro)\b
  captures:
  match: keyword.control.import.nsis
```

Regards,
Robin

**Comment by idleberg** [comment]
@FichteFoll Any idea why `convert_syntax.py` would produce this?

**Comment by FichteFoll** [comment]
@idleberg do you happen to have the source for that pattern?

**Comment by idleberg** [comment]
The old `[tmLanguage](https://github.com/SublimeText/NSIS/blob/st2-master/NSIS.tmLanguage#L234-L243)` is the source of the pattern.

As for the pattern itself, I'm not sure about its origin. I think I can say that I have broad overview of syntax files for other editors, but don't recall ever seeing the distinction from [other compiler commands](https://github.com/SublimeText/NSIS/blob/st2-master/NSIS.tmLanguage#L20-L24). Since I never questions the authors motive for this particular distinction, I never touched that pattern.

**Comment by FichteFoll** [comment]
Well, the same errorneous pattern is present in the file you linked (NSIS.tmLanguage), so I wouldn't fault the converter for this, except that it didn't panic.

**Comment by robotroll** [comment]
@idleberg I installed the package via Package Control. It always worked without a problem until I updated Sublime and restartet it. Since I was working on an _.nsh_ file the error message popped up immediately.
